# Generated by Django 4.1.3 on 2022-11-14 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('name_kana', models.CharField(blank=True, max_length=40)),
                ('tel', models.CharField(max_length=40)),
                ('tel2', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='名前', max_length=40)),
                ('sex', models.BooleanField(help_text='オス=True、メス=False')),
                ('birth', models.DateField(help_text='誕生日', null=True)),
                ('death', models.DateField(help_text='死亡日', null=True)),
                ('breed', models.ForeignKey(blank=True, help_text='柴犬･ネザーランドドワーフなど', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.petbreed')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('memo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.memo')),
                ('type', models.ForeignKey(blank=True, help_text='犬･猫･うさぎなど', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pettype')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='memo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.memo'),
        ),
    ]
