# Generated by Django 4.1.3 on 2022-11-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_pet_petbreed_pettype_petmemo_pet_breed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='death',
            field=models.DateField(blank=True, help_text='死亡日', null=True),
        ),
    ]
