# Generated by Django 4.1.6 on 2023-02-06 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_created_customer_updated_pet_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petbreed',
            name='type',
            field=models.ForeignKey(default=1, help_text='ペットタイプ', on_delete=django.db.models.deletion.CASCADE, related_name='pet_type', to='core.customer'),
            preserve_default=False,
        ),
    ]
