# Generated by Django 4.1.3 on 2022-11-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_type_pettype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petbreed',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pettype',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
