# Generated by Django 4.1.3 on 2022-11-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_petbreed_name_alter_pettype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.BooleanField(blank=True, help_text='オス=True、メス=False', null=True),
        ),
    ]
