# Generated by Django 4.1.3 on 2022-11-28 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pet_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmemo',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='core.pet'),
        ),
    ]
