# Generated by Django 4.1.7 on 2023-02-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='line',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
    ]
