# Generated by Django 4.1.6 on 2023-02-08 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_petbreed_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(blank=True, help_text='柴犬･ネザーランドドワーフなど', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.petbreed'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.ForeignKey(blank=True, help_text='犬･猫･うさぎなど', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.pettype'),
        ),
    ]
