# Generated by Django 4.1.3 on 2022-11-29 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_petmemo_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PetLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.IntegerField(blank=True, help_text='体重', null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='customer',
            field=models.ForeignKey(help_text='顧客ナンバー', on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
        ),
        migrations.AddField(
            model_name='pet',
            name='dislike',
            field=models.ManyToManyField(blank=True, help_text='苦手なこと', null=True, to='core.petdislike'),
        ),
        migrations.AddField(
            model_name='pet',
            name='like',
            field=models.ManyToManyField(blank=True, help_text='好きなこと', null=True, to='core.petlike'),
        ),
    ]
