# Generated by Django 4.1.7 on 2023-02-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customer_email_customer_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='line',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
