# Generated by Django 4.1.3 on 2022-11-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_petdislike_petlike_pet_weight_alter_pet_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='dislike',
            field=models.ManyToManyField(blank=True, help_text='苦手なこと', to='core.petdislike'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='like',
            field=models.ManyToManyField(blank=True, help_text='好きなこと', to='core.petlike'),
        ),
    ]
