# Generated by Django 4.1.3 on 2022-11-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_pet_dislike_alter_pet_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='dislike',
            new_name='dislikes',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='like',
            new_name='likes',
        ),
    ]
