---
name: Checks

on: [ push ]


jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-20.04
    env:
      DJANGO_SECRET_KEY: secret_key
      MARIADB_ROOT_PASSWORD: password
      DB_NAME: sitter-devdb
      DB_USER: dbuser
      DB_PASSWORD: password
    steps:
      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Start Containers
        run: docker-compose up -d --build

      - name: Wait for Database
        run: docker-compose run --rm backend sh -c "python manage.py wait_for_db"

      - name: Grant setting
        run: docker-compose exec -T database mysql --protocol=tcp -P 3306 -u root -p$MARIADB_ROOT_PASSWORD -e "GRANT ALL PRIVILEGES ON test_database.* TO 'dbuser'@'%';"

      - name: Migrate Database
        run: docker-compose run --rm backend sh -c "python manage.py migrate"

      - name: Test Backend
        run: docker-compose run --rm backend sh -c "python manage.py test"

      - name: Lint Backend
        run: docker-compose run --rm backend sh -c "flake8"